import { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "NewsPaper",
  description: "Generated by create next NewsPaper",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/favicon.ico" sizes="any" />
      <body className="bg-gray-200">
        {children}
      </body>
    </html>
  );
}
